services:
  - type: web
    name: dazzlodocs-converter
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
    disk:
      name: dazzlodocs-disk
      mountPath: /app/outputs
      sizeGB: 1